ccflags-y += -Idrivers/media/platform/msm/ais
ccflags-y += -Idrivers/media/platform/msm/ais/common
ccflags-y += -Idrivers/media/platform/msm/ais/sensor/io
ccflags-y += -Idrivers/media/platform/msm/ais/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/ais/isp
obj-$(CONFIG_MSM_AIS) += early_camera_smmu.o msm_early_cam_handoff.o
